# vim: filetype=yaml.ansible:foldmarker=<<<,>>>:foldmethod=marker :
---
- hosts: localhost

  vars:
    essentials: [vim, git, curl, wget, openssh, base-devel, ttf-ubuntu-font-family]
    tools: [dictd, python-pip, zsh, npm, ruby, feh, rxvt-unicode]
    i3_pkgs: [i3-gaps, dmenu, i3lock, i3status, perl-json-xs, perl-anyevent-i3]

  vars_prompt:
    - name: aur_cmd
      prompt: AUR helper command
      default: aurman
      private: no

  tasks:

    - name: "Install essentials"
      pacman:
        name: '{{essentials + tools + i3_pkgs}}'
        state: present
      become: yes

    - name: Install hangups and rtv
      pip:
        name: hangups, rtv
        state: present
        extra_args: --user

    - name: Install English dictionary
      command: '{{aur_cmd}} -S --noconfirm --noedit --pgp_fetch dict-gcide'

    - name: Enable dictd service
      service:
        name: dictd
        state: started
        enabled: yes
      become: yes

