# vim: filetype=yaml.ansible:foldmarker=<<<,>>>:foldmethod=marker :
---
# Install packages <<<1
- hosts: localhost
  # The above hosts entry is required for ensuring facts have been gathered
  # (used on the when clause below).

- import_playbook: arch.yml
  when: ansible_distribution == 'Archlinux'
# >>>1

- hosts: localhost

  vars:
    dotfiles: [emacs, gitconfig, vimrc, zshrc, npmrc]
    username: '{{ ansible_env.USER }}'
    userhome: '{{ ansible_env.HOME }}'
    dotfiles_path: '{{userhome}}/repos/dotfiles'

  tasks:

    - name: Clone essential repositories
      git:
        repo: "https://github.com/{{item}}.git"
        dest: "{{userhome}}/repos/{{item|basename}}"
        update: no
      loop:
        - cenouro/dotfiles
        - seebi/dircolors-solarized
        - zsh-users/zsh-completions
        - zsh-users/zsh-history-substring-search
        - zsh-users/zsh-syntax-highlighting

    # rbenv tasks <<<1
    - name: Clone rbenv
      git:
        repo: 'https://github.com/rbenv/rbenv.git'
        dest: '{{userhome}}/.rbenv'
        update: no

    - name: "Compile dynamic bash extension"
      shell: src/configure && make -C src
      args:
        chdir: ~/.rbenv

    - name: Register rbenv_root
      command: '{{userhome}}/.rbenv/bin/rbenv root'
      register: rbenv_root

    - name: Clone ruby-build
      git:
        repo: 'http://github.com/rbenv/ruby-build.git'
        dest: '{{rbenv_root.stdout}}/plugins/ruby-build'
        update: no
    # >>>1

    - name: Link dotfiles
      file:
        state: link
        src: '{{dotfiles_path}}/{{item}}'
        path: '{{userhome}}/.{{item}}'
      loop: '{{dotfiles}}'

    - name: Create npm folder
      file:
        state: directory
        path: '{{userhome}}/.npm-packages'

    - name: Link dircolors
      file:
        state: link
        src: '{{userhome}}/repos/dircolors-solarized/dircolors.256dark'
        path: '{{userhome}}/.dircolors'

    - name: Create npm directory
      file:
        state: directory
        path: '{{userhome}}/.npm-packages'

    - name: '$(which zsh)'
      command: which zsh
      register: which_zsh

    - name: Set zsh as default shell
      user:
        name: '{{ username }}'
        shell: '{{ which_zsh.stdout }}'
      become: yes

    # Install vim plugins with Vundle <<<1
    - name: Clone vundle
      git:
        repo: 'https://github.com/VundleVim/Vundle.vim.git'
        dest: '{{userhome}}/.vim/bundle/Vundle.vim'
        update: no

    - name: Disable vim colorschemes to avoid errors
      replace:
        path: '{{dotfiles_path}}/vimrc'
        regexp: '^(colorscheme.*)'
        replace: '"ansible\1'

    - name: Install vim plugins with Vundle
      shell: "vim -E -s -c 'source {{dotfiles_path}}/vimrc' +PluginInstall +qa"

    - name: Enable vim colorschemes
      replace:
        path: '{{dotfiles_path}}/vimrc'
        regexp: '^"ansible(.*)'
        replace: '\1'
    # >>>1

