---
asdf_nodejs_deps:
  - gcc-c++
  - make
  - python3
  - python3-pip

asdf_ruby_deps:
  - autoconf
  - bzip2
  - gcc
  - gdbm-devel
  - libffi-devel
  - libyaml-devel
  - make
  - ncurses-devel
  - openssl-devel
  - patch
  - readline-devel
  - rust
  - zlib-devel
...
