---
- name: Install asdf-ruby (ruby-build) dependencies
  ansible.builtin.apt:
    package:
      - autoconf
      - patch
      - build-essential
      - rustc
      - libssl-dev
      - libyaml-dev
      - libreadline6-dev
      - zlib1g-dev
      - libgmp-dev
      - libncurses5-dev
      - libffi-dev
      - libgdbm6
      - libgdbm-dev
      - libdb-dev
      - uuid-dev
    state: present
  become: true

- name: Install asdf-ruby plugin
  ansible.builtin.shell:
    cmd: |
      source {{ HOME|quote }}/.bashrc
      asdf plugin add ruby https://github.com/asdf-vm/asdf-ruby.git
    executable: /usr/bin/bash
    creates: '{{ HOME }}/.asdf/plugins/ruby/'
...
