---
- name: Install asdf-ruby (ruby-build) dependencies
  ansible.builtin.package:
    name: '{{ asdf_ruby_deps }}'
    state: present
  become: true

- name: Install asdf-ruby plugin
  ansible.builtin.shell:
    cmd: |
      source {{ HOME|quote }}/.asdf/asdf.sh
      asdf plugin add ruby https://github.com/asdf-vm/asdf-ruby.git
    executable: /usr/bin/bash
    creates: '{{ HOME }}/.asdf/plugins/ruby/'
...
