---
deb_app_launchers_dir: '/usr/share/applications/'
user_app_launchers_dir: '{{ HOME }}/.local/share/applications'

deb:
  mpv:
    desktop: '{{ deb_app_launchers_dir }}/mpv.desktop'

user:
  mpv:
    desktop: '{{ user_app_launchers_dir }}/mpv.desktop'
...
