---
snap_app_launchers_dir: '/var/lib/snapd/desktop/applications'
user_app_launchers_dir: '{{ HOME }}/.local/share/applications'

snap:
  firefox:
    desktop: '{{ snap_app_launchers_dir }}/firefox_firefox.desktop'

user:
  firefox:
    desktop: '{{ user_app_launchers_dir }}/firefox_firefox.desktop'
...
