---
- name: Install essential packages
  ansible.builtin.dnf:
    name:
      - chromium
      - firefox
      - mpv
      - transmission
      - tree
      - wget
    state: present
  become: true

- name: Install essential flatpaks
  community.general.flatpak:
    name:
      - io.bassi.Amberol
      - org.nickvision.tagger
      - org.nickvision.tubeconverter
    state: present
...
