---
- name: Install applications
  include_tasks: '{{ DISTRO }}.yml'

- name: 'MPV: ensure config folder'
  ansible.builtin.file:
    path: '{{ XDG_CONFIG_HOME }}/mpv'
    state: directory

- name: 'MPV: link config file'
  ansible.builtin.file:
    src: '{{ PWD }}/mpv.conf'
    dest: '{{ XDG_CONFIG_HOME }}/mpv/mpv.conf'
    state: link

- name: 'TRANSMISSION: ensure config folder'
  ansible.builtin.file:
    path: '{{ XDG_CONFIG_HOME }}/transmission'
    state: directory

- name: 'FIREFOX: Enable pixel-perfect scrolling'
  ansible.builtin.blockinfile:
    path: '{{ item.path }}'
    block: '{{ item.block }}'
    prepend_newline: true
    append_newline: true
    marker: '# {mark} Ansible Managed Block | FIREFOX: Enable pixel-perfect scrolling'
    create: true
  loop:
    - path: '{{ HOME }}/.xprofile'
      block: 'export MOZ_USE_XINPUT2=1'
    - path: '{{ XDG_CONFIG_HOME }}/environment.d/envvars.conf'
      block: 'MOZ_ENABLE_WAYLAND=1'

- name: Load variables pertinent to '{{ computer_name }}'
  ansible.builtin.include_vars: '{{ computer_name_nospaces }}.yml'

- name: Create /mnt/HDD
  ansible.builtin.file:
    path: /mnt/HDD
    state: directory
  become: true

- name: 'FSTAB: add user mount points'
  ansible.builtin.blockinfile:
    path: /etc/fstab
    block: |
      UUID={{ data_device_uuid }} /mnt/HDD                              btrfs   noatime,space_cache=v2,compress=zstd    0   0
      /mnt/HDD/@music                           /home/{{ ansible_facts.user_id }}/Music                   none    bind,x-gvfs-hide                        0   0
      /mnt/HDD/@videos                          /home/{{ ansible_facts.user_id }}/Videos                  none    bind,x-gvfs-hide                        0   0
      /mnt/HDD/@transmission                    /home/{{ ansible_facts.user_id }}/.config/transmission    none    bind,x-gvfs-hide                        0   0
    prepend_newline: true
    append_newline: true
  become: true
  notify: 'mount fstab'
...
