---
- hosts: localhost
  vars:
    dotfiles: ['vimrc']

  tasks:
    - name: Configure git
      git_config:
        name: '{{ item.name }}'
        value: '{{ item.value }}'
        scope: global
      loop:
        - {name: 'user.name', value: 'Mario Maia'}
        - {name: 'user.email', value: '101b147ch@gmail.com'}
        - {name: 'core.editor', value: 'vim'}

    - name: "Configure shell"
      shell: chsh -s $(which zsh)
      become: yes

    - name: "Initialize dotfiles directory"
      git:
        repo: "https://github.com/cenouro/dotfiles"
        dest: "~/dotfiles"
        update: no

    - name: "Backup distro's files"
      shell: mv .{{item}} .{{item}}.distro.back
      args:
        chdir: ~/
        creates: .{{item}}.distro.back
        removes: .{{item}}
      with_items: "{{dotfiles}}"

    - name: "Setup links"
      file:
        src: ~/dotfiles/{{item}}
        path: ~/.{{item}}
        state: link
      with_items: "{{dotfiles}}"

