---
- name: Install dconf-editor and community.general.dconf dependency
  ansible.builtin.package:
    name:
      - dconf-editor
      - python3-psutil
    state: present
  become: true

- name: Disable natural scroll
  community.general.dconf:
    key: "/org/gnome/desktop/peripherals/touchpad/natural-scroll"
    value: "false"
    state: present

- name: Allow sound volume to go beyond 100%
  community.general.dconf:
    key: "/org/gnome/desktop/sound/allow-volume-above-100-percent"
    value: "true"
    state: present

- name: Always show accessibility menu in system tray
  community.general.dconf:
    key: "/org/gnome/desktop/a11y/always-show-universal-access-status"
    value: "true"
    state: present

- name: Set Power Button behavior to suspend
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/power/power-button-action"
    value: "'suspend'"
    state: present
...
