---
- name: Create config directory
  ansible.builtin.file:
    path: '{{ XDG_CONFIG_HOME }}/git'
    state: directory

- name: Link gitconfig
  ansible.builtin.file:
    src: '{{ PWD }}/gitconfig'
    dest: '{{ XDG_CONFIG_HOME }}/git/config'
    state: link

- name: Enforce use of XDG user directory
  ansible.builtin.file:
    path: '{{ HOME }}/.gitconfig'
    state: absent
...
