---
chruby:
  repo: https://github.com/postmodern/chruby.git
  tag: v0.3.9
  folder: '{{ HOME }}/github/chruby.git'

ruby_install:
  repo: https://github.com/postmodern/ruby-install.git
  tag: v0.9.0
  folder: '{{ HOME }}/github/ruby-install.git'

deps_for:
  ruby_install:
    - curl
    - wget
  building_ruby:
    - build-essential
    - bison
    - zlib1g-dev
    - libyaml-dev
    - libssl-dev
    - libgdbm-dev
    - libreadline-dev
    - libffi-dev
...
