---
- name: Install dependencies
  ansible.builtin.apt:
    package: '{{ item }}'
    state: present
  loop:
    - '{{ deps_for.ruby_install }}'
    - '{{ deps_for.building_ruby }}'
  become: yes

- name: Clone chruby repository
  ansible.builtin.git:
    repo: '{{ chruby.repo }}'
    dest: '{{chruby.folder }}'
    version: '{{ chruby.tag }}'
    depth: 1
  notify: Install chruby

- name: Clone ruby-install repository
  ansible.builtin.git:
    repo: '{{ ruby_install.repo }}'
    dest: '{{ ruby_install.folder }}'
    version: '{{ ruby_install.tag }}'
    depth: 1
  notify: Install ruby-install

- name: Ensure chruby is sourced in ~/.bashrc
  ansible.builtin.blockinfile:
    block: |
      source /usr/local/share/chruby/chruby.sh
      source /usr/local/share/chruby/auto.sh
    path: '{{ HOME }}/.bashrc'
    insertafter: EOL
    marker_begin: 'CHRUBY BEGIN'
    marker_end: 'CHRUBY END'

- name: Set system Ruby as the default
  ansible.builtin.lineinfile:
    line: 'chruby system'
    path: '{{ HOME }}/.bash_profile'
    create: true
...
