---
- name: Install Chromium snap
  community.general.snap:
    name: chromium
    channel: stable
    state: present
  become: true

- name: Copy Chromium app launcher
  ansible.builtin.copy:
    src: '{{ snap.chromium.desktop }}'
    dest: '{{ user.chromium.desktop }}'
    mode: preserve
    force: false

- name: Customize Chromium app launcher
  ansible.builtin.lineinfile:
    path: '{{ user.chromium.desktop }}'
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
    firstmatch: true
    backrefs: true
  loop:
    - regexp: '^Name=Chromium Web Browser$'
      line: 'Name=Chromium'
    - regexp: '^Icon=/snap/chromium/(?!current).*?/(.*)$'
      line: 'Icon=/snap/chromium/current/\1'
...
