---
- name: Install Firefox snap
  community.general.snap:
    name: firefox
    channel: stable
    state: present
  become: true

- name: Enable pixel-perfect scrolling in Firefox
  ansible.builtin.lineinfile:
    path: '{{ item.path }}'
    line: '{{ item.line }}'
    state: present
    create: True
  loop:
    - path: '{{ HOME }}/.xprofile'
      line: 'export MOZ_USE_XINPUT2=1'
    - path: '{{ XDG_CONFIG_HOME }}/environment.d/envvars.conf'
      line: 'MOZ_ENABLE_WAYLAND=1'

- name: Copy Firefox app launcher
  ansible.builtin.copy:
    src: '{{ snap.firefox.desktop }}'
    dest: '{{ user.firefox.desktop }}'
    mode: preserve
    force: false
  notify: Customize Firefox app launcher
...
