---
- name: Install essential packages
  ansible.builtin.apt:
    package:
      - mpv
      - transmission
      - tree
      - wget
    state: present
  become: true

- name: Install essential snaps
  community.general.snap:
    name:
      - amberol
      - bitwarden
      - chromium
      - firefox
      - onlyoffice-desktopeditors
      - tagger
      - tube-converter
    state: present
  become: true

- name: Copy mpv app launcher
  ansible.builtin.copy:
    src: '{{ deb.mpv.desktop }}'
    dest: '{{ user.mpv.desktop }}'
    mode: preserve
    force: false

- name: Hide mpv app launcher
  ansible.builtin.lineinfile:
    path: '{{ user.mpv.desktop }}'
    line: 'NoDisplay=true'
    insertbefore: 'Name=mpv Media Player'
    firstmatch: true

- name: Enable pixel-perfect scrolling in Firefox
  ansible.builtin.lineinfile:
    path: '{{ item.path }}'
    line: '{{ item.line }}'
    state: present
    create: True
  loop:
    - path: '{{ HOME }}/.xprofile'
      line: 'export MOZ_USE_XINPUT2=1'
    - path: '{{ XDG_CONFIG_HOME }}/environment.d/envvars.conf'
      line: 'MOZ_ENABLE_WAYLAND=1'
...
