---
- name: Install essential packages
  ansible.builtin.apt:
    package:
      - transmission
      - tree
      - wget
    state: present
  become: true

- name: Include Firefox tasks
  include_tasks: firefox-snap.yml

- name: Include Chromium tasks
  include_tasks: chromium-snap.yml

- name: Include mpv tasks
  include_tasks: mpv.yml
...
