---
- name: Customize Firefox app launcher
  ansible.builtin.lineinfile:
    path: '{{ user.firefox.desktop }}'
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
  loop:
    - { regexp: '^Name=Firefox', line: 'Name=Firefox' }
    - regexp: '^Icon=/snap/firefox/'
      line: 'Icon=/snap/firefox/current/default256.png'
...
